### ISSUE TITLE
FdSearchInput triggers search event on every keystroke (but shouldn't)

### ISSUE THREAD

**Issue by khmmrl** [SAP/fundamental-vue#265]
Hi,

there is a small issue with FdSearchInput (see below).

Best regards,
Kay

#### Is this a bug, enhancement, or feature request?
Bug

#### Briefly describe your proposal.
FdSearchInput triggers search event on every keystroke, but should only trigger it on Enter or on click on search button.

#### Which versions of Vue.JS and Fundamental Vue are affected? (If this is a feature request, use current version.)
current

#### If this is a bug, please provide steps for reproducing it.
Use FdSearchInput as shown below.

#### Please provide relevant source code if applicable.
`<FdSearchInput
                placeholder="Search..."
                @search="search" />`
`'search': function (searchString) {
      console.log(searchString);
    },`

#### Is there anything else we should know?
Maybe have to events: "liveSearch" -> every keystroke; "search" -> enter or search button

**Comment by ChristianKienle** [comment]
Just a heads up @khmmrl - I am currently improving `FdSearchInput`. Those improvements include a fix for your issue. I think a workaround could be to listen for `@change.native`-events.

Once you update to `v0.2` (not yet released) you will probably have to change your code in order to get the new `FdSearchInput`. Breaking changes are still very likely. :/

**Comment by ChristianKienle** [comment]
@khmmrl PR #279 will fix that once merged . 😄🎉

**Comment by ChristianKienle** [comment]
@khmmrl fixed. 0.3 is available via npm. Documentation not yet updated due to technical problems but we are working on this.
