### ISSUE TITLE
Internationalization and localization

### ISSUE THREAD

**Issue by eggward** [SAP/fundamental-vue#79]
Would there be a some built in internationalization feature in fundamental-vue? Similar to OpenUI5 having i18n files for their components like its calendar.

If this will not be supported then components would need to offer the api to do this. One example would be the pagination component having tooltip properties for the next and previous buttons.

**Comment by ChristianKienle** [comment]
Thank you very much for this question, @eggward. From experience I know that localization and internationalization is not a trivial subject. Because of that (and a few other reasons) the answer requires a few more words.

But to summarize the longer answer below: 

*At this moment, there is no logic in Fundamental Vue that is trying to specifically solve localisation and internationalization related issues.*

That being said I (and others on the team probably agree) am very well aware that we have to address localisation and internationalization at some point. IMHO this is something that must be done.

In one of our next team calls I will bring up this topic and see what others think. However you don't have to wait for Fundamental Vue to solve this problem since there are already several options for you. Some of the work that has to be done can already be done by the application developer (even though this is of course far from perfect). Take the calendar component for example. Today you can already customize the month and day names like this:

```
<FdCalendar 
	:dayNames="['Montag', 'Dienstag', 'Mittwoch', …]"
	:monthNames="['Januar', 'Februar', …]"
/>
```

You asked specifically about the pagination component and localized tooltips. By asking that question you actually discovered a missing feature. :) My personal thought process is like this:

Every component should be localizable or localized by default. This means a component which displays static text/icons (eg. "next"-buttons) should either be fully localized out of the box and/or make those texts configurable so that at least application developer can localize those things on their own.

Also please note that localization and internationalization is usually supported by any Vue UI library. If you were to implement it yourself you would do something like this in your `main.js` file:

```
new Vue({
  locale: 'en_US' // or something the user has selected in preferences
}).mount("#app");
```

Then you can access the current locale in any component like this:

```
export default {
  methods: {
    helloWorld() {
       console.log(this.$options.locale) // -> en_US
    }
  }
}
```

Here is what will happen now:

1. I have created a PR (#83) that adds a note about localization to our **New Component**-guide.
2. There is already an issue (#62) that will solve the tooltip problem (at least make most of them them configurable.
3. I will bring the issue you addressed up in one of our next calls. This will most likely result in the creation of follow up issues.

If you feel not satisfied with the state of localization shortly before we release 1.0 or if you have more questions please create a new issue or reopen this one.
