### ISSUE TITLE
Side Navigation with submenu maintains highlight on change 

### ISSUE THREAD

**Issue by Kzai** [SAP/fundamental-vue#81]
Menu items with a submenu maintain highlight (selected) styling when the menu item selection is changed. 

![image](https://user-images.githubusercontent.com/7649393/50364103-7f2d7780-0566-11e9-84f1-8437f1f8535c.png)

IMO, the menu item should close when the user selects another item and should no longer be highlighted.

**Comment by ChristianKienle** [comment]
This is intentional. It is the same as here: https://sap.github.io/fundamental/components/side-navigation.html

That being said: Back then when I first worked on this component, I already was unsure about this behaviour. It it possible that it is the way it is (in the Fundamentals Guide) because they made a mistake or lack the interactive part of the whole story. :D

We should clarify that.
